FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
RUN ls
COPY ["SispeServiciosApiGateway/SispeServiciosApiGateway.csproj", "SispeServiciosApiGateway/"]
COPY ["SispeServiciosApiGateway/Ocelot.json", "SispeServiciosApiGateway/"]

RUN dotnet restore "SispeServiciosApiGateway/SispeServiciosApiGateway.csproj"
COPY . .
WORKDIR "/src/SispeServiciosApiGateway"
RUN dotnet build "SispeServiciosApiGateway.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "SispeServiciosApiGateway.csproj" -c Debug -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SispeServiciosApiGateway.dll"]