// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SispeServicios.Api.Intermediacion.Persistencia;

#nullable disable

namespace SispeServicios.Api.Intermediacion.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221209221232_56")]
    partial class _56
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.EmpresaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.EmpresaSedeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmpresaSede");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.EmpresaSedeResponsableModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaSedeId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaUsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmpresaSedeResponsable");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.EmpresaUsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmpresaUsuario");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteConocimientoCompetenciaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConocimientoCompetenciaId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacanteId");

                    b.ToTable("VacanteConocimientosCompetencia");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteDiscapacidadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiscapacidadId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacanteId");

                    b.ToTable("VacanteDiscapacidad");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteEstadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VacanteEstado");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteHabilidadDestrezaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HabilidadDestrezaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacanteId");

                    b.ToTable("VacanteHabilidadDestreza");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteIdiomaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Conversacional")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("Escritura")
                        .HasColumnType("int");

                    b.Property<int>("Escucha")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IdiomaId")
                        .HasColumnType("int");

                    b.Property<int>("Lectura")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacanteId");

                    b.ToTable("VacanteIdioma");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AptaParaPersonasConDiscapacidad")
                        .HasColumnType("bit");

                    b.Property<int?>("AreaEmpresaId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaLicenciaCarroId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaLicenciaMotoId")
                        .HasColumnType("int");

                    b.Property<bool?>("CompensacionAdicional")
                        .HasColumnType("bit");

                    b.Property<bool?>("Confidencial")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionCapacitacionEspecifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionCertificacionEspecifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionCompensacionAdicional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionExperienciaEspecifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("FechaEstimadaOcupacionCargo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteEnvioHv")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("FechaVencimientoVacante")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormacionTitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GestionadaPorPrestador")
                        .HasColumnType("bit");

                    b.Property<bool?>("GetionadaPorPrestadorAlterno")
                        .HasColumnType("bit");

                    b.Property<bool?>("Graduado")
                        .HasColumnType("bit");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacionAdicional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JornadaLaboralId")
                        .HasColumnType("int");

                    b.Property<int?>("ModalidadTrabajoId")
                        .HasColumnType("int");

                    b.Property<int?>("NivelMinimoEstudioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeriodicidadSalarialId")
                        .HasColumnType("int");

                    b.Property<int?>("PuestosRequeridos")
                        .HasColumnType("int");

                    b.Property<int?>("RangoSalarialFinalId")
                        .HasColumnType("int");

                    b.Property<int?>("RangoSalarialInicailId")
                        .HasColumnType("int");

                    b.Property<bool?>("RequiereCapacitacionEspecifica")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiereCertificacionEspecifica")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiereExperienciaEspecifica")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiereExperienciaGeneral")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiereLicenciaConduccion")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiereLicenciaConduccionMoto")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiereViajarPorTrabajo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SectorEconomicoId")
                        .HasColumnType("int");

                    b.Property<string>("SolicitudAutorizacionExcepcionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SolicitudExcepcionalidad")
                        .HasColumnType("bit");

                    b.Property<int?>("SubsectorEconomicoId")
                        .HasColumnType("int");

                    b.Property<bool?>("TendraPersonasCargo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TiempoExperiencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TipoContratoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoSalariolId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("VisibilidadSalario")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Vacante");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteMotivoExepcionalidadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MotivosExepcionalidadId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacanteId");

                    b.ToTable("VacanteMotivoExepcionalidad");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteOcupacionRelacionadaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OcupacionesRelacionadoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacanteId");

                    b.ToTable("VacanteOcupacionRelacionada");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacantePrestadorAlternoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PrestadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacanteId");

                    b.ToTable("VacantePrestadorAlterno");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteUbicacionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartamentoID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LocalidadComunaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipioID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroPuestos")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacanteId");

                    b.ToTable("VacanteUbicacion");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.EmpresaSedeModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.EmpresaModel", "Empresa")
                        .WithMany("Sedes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.EmpresaUsuarioModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.EmpresaModel", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteConocimientoCompetenciaModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", "Vacante")
                        .WithMany("ConocimientosCompetencias")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteDiscapacidadModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", "Vacante")
                        .WithMany("Discapacidades")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteHabilidadDestrezaModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", "Vacante")
                        .WithMany("HabilidadesDestrezas")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteIdiomaModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", "Vacante")
                        .WithMany("Idiomas")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.VacanteEstadoModel", "Estado")
                        .WithMany("Vacantes")
                        .HasForeignKey("EstadoId");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteMotivoExepcionalidadModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", "Vacante")
                        .WithMany("MotivosExepcionalidad")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteOcupacionRelacionadaModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", "Vacante")
                        .WithMany("OcupacionesRelacionadas")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacantePrestadorAlternoModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", "Vacante")
                        .WithMany("PrestadoresAlternos")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteUbicacionModel", b =>
                {
                    b.HasOne("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", "Vacante")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.EmpresaModel", b =>
                {
                    b.Navigation("Sedes");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteEstadoModel", b =>
                {
                    b.Navigation("Vacantes");
                });

            modelBuilder.Entity("SispeServicios.Api.Intermediacion.Modelo.VacanteModel", b =>
                {
                    b.Navigation("ConocimientosCompetencias");

                    b.Navigation("Discapacidades");

                    b.Navigation("HabilidadesDestrezas");

                    b.Navigation("Idiomas");

                    b.Navigation("MotivosExepcionalidad");

                    b.Navigation("OcupacionesRelacionadas");

                    b.Navigation("PrestadoresAlternos");

                    b.Navigation("Ubicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
