apiVersion: v1
kind: Service
metadata:
  name: #{NAME}#-svc
  namespace: #{NS}#
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet1"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: #{CPORT}#
    protocol: TCP
    name: https
  selector:
    app: #{NAME}#